functionalAreas:
  directory:
    enabled: true
    capability:
      index: DIRECTORY
  camps:
    enabled: false
  tasks:
    enabled: false
  documents:
    enabled: false
    exposed: false
  articles:
    enabled: false
  admin:
    enabled: true
    capability:
      index: ALL
  search:
    enabled: true
    capability:
      index: LOGIN

searchConfigured:
  Users: true
  Documents: true
  Sections: true
